-- ============================================================================
-- ATHLEAT — allow `v3` rows in public.meal_analysis
-- ============================================================================
-- Why:
--   When the coach picks a V3 carousel card and presses "Send to athlete",
--   we want to persist that selection as a meal_analysis row (version 'v3')
--   so the V3 pick survives reloads, shows up in the Kez side panel, and
--   becomes part of the athlete's V1 → V2 → V3 progression on the dashboard.
--
--   The original schema (backend/sql/2026_05_10_meal_analysis_carousel.sql)
--   pinned `version` to ('v1','v2'). This migration relaxes that CHECK to
--   ('v1','v2','v3'). Idempotent — safe to re-run.
--
-- Scope:
--   • Drops the existing `version` CHECK constraint (whatever its name).
--   • Adds a new one with v3 allowed.
--   • No data is migrated — existing v1/v2 rows continue to validate.
-- ============================================================================

DO $$
DECLARE
  con_name text;
BEGIN
  -- Find every CHECK constraint on public.meal_analysis whose definition
  -- mentions the `version` column and drop them all. Constraint names are
  -- auto-generated by Postgres when none was supplied (e.g.
  -- `meal_analysis_version_check`), so we look it up dynamically.
  FOR con_name IN
    SELECT c.conname
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
     WHERE n.nspname = 'public'
       AND t.relname = 'meal_analysis'
       AND c.contype = 'c'
       AND pg_get_constraintdef(c.oid) ILIKE '%version%'
  LOOP
    EXECUTE format(
      'ALTER TABLE public.meal_analysis DROP CONSTRAINT %I',
      con_name
    );
  END LOOP;
END
$$;

ALTER TABLE public.meal_analysis
  ADD CONSTRAINT meal_analysis_version_check
  CHECK (version IN ('v1', 'v2', 'v3'));

-- Verification (run manually):
--   SELECT pg_get_constraintdef(c.oid)
--     FROM pg_constraint c
--     JOIN pg_class t ON t.oid = c.conrelid
--     JOIN pg_namespace n ON n.oid = t.relnamespace
--    WHERE n.nspname = 'public' AND t.relname = 'meal_analysis' AND c.contype = 'c';
