-- =============================================================================
-- ATHLEAT — Meal analysis + V3 carousel drafts + carousel settings
-- Idempotent. Run in Supabase SQL editor or psql.
-- =============================================================================

-- Optional: Kerry-configurable carousel count (read by Next /api/kez/meal-carousel)
ALTER TABLE public.eer_config
  ADD COLUMN IF NOT EXISTS carousel_settings jsonb DEFAULT '{"suggestion_count": 5}'::jsonb;

-- Verified flag for meals generated by Kez pending Kerry review
ALTER TABLE public.meals
  ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT true;

UPDATE public.meals SET is_verified = true WHERE is_verified IS NULL;

-- ---------------------------------------------------------------------------
-- meal_analysis — one row per Kez run (student, mission, slot, v1|v2)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.meal_analysis (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id        uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  mission_id        text NOT NULL,
  slot_id           text NOT NULL,
  version           text NOT NULL CHECK (version IN ('v1', 'v2')),
  image_url         text,
  meal_text         text,
  load_day          text NOT NULL CHECK (load_day IN ('Lower', 'Moderate', 'High')),
  category          text,
  vision_raw        jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolved_items    jsonb NOT NULL DEFAULT '[]'::jsonb,
  macro_totals      jsonb NOT NULL DEFAULT '{}'::jsonb,
  target_band       jsonb NOT NULL DEFAULT '{}'::jsonb,
  vs_targets        jsonb NOT NULL DEFAULT '{}'::jsonb,
  feedback_text     text,
  feedback_status   text NOT NULL DEFAULT 'draft'
    CHECK (feedback_status IN ('draft', 'approved')),
  confidence        numeric(5,4),
  needs_correction  boolean NOT NULL DEFAULT false,
  flags             text[] NOT NULL DEFAULT '{}'::text[],
  model_meta        jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_meal_analysis_student
  ON public.meal_analysis (student_id);
CREATE INDEX IF NOT EXISTS idx_meal_analysis_mission_slot
  ON public.meal_analysis (student_id, mission_id, slot_id, version);
CREATE INDEX IF NOT EXISTS idx_meal_analysis_created
  ON public.meal_analysis (created_at DESC);

ALTER TABLE public.meal_analysis ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'meal_analysis'
      AND policyname = 'meal_analysis_service_all'
  ) THEN
    CREATE POLICY "meal_analysis_service_all" ON public.meal_analysis
      FOR ALL USING (true);
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- meal_carousel_draft — unverified Kez-generated carousel cards for review
-- `created_meal_id` MUST match `public.meals.id` (legacy stacks use bigint/bigserial;
-- v4-only schemas may use uuid — adjust this column type if FK creation fails.)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.meal_carousel_draft (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  analysis_id     uuid REFERENCES public.meal_analysis(id) ON DELETE SET NULL,
  student_id      uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  mission_id      text NOT NULL,
  slot_id         text NOT NULL,
  payload         jsonb NOT NULL,
  status          text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  created_meal_id bigint REFERENCES public.meals(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_meal_carousel_draft_student
  ON public.meal_carousel_draft (student_id);
CREATE INDEX IF NOT EXISTS idx_meal_carousel_draft_status
  ON public.meal_carousel_draft (status);

-- If this table existed from an older script with uuid `created_meal_id` against bigint `meals.id`, repair it.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'meal_carousel_draft'
      AND c.column_name = 'created_meal_id'
      AND c.data_type = 'uuid'
  ) AND EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'meals'
      AND c.column_name = 'id'
      AND c.data_type = 'bigint'
  ) THEN
    ALTER TABLE public.meal_carousel_draft
      DROP CONSTRAINT IF EXISTS meal_carousel_draft_created_meal_id_fkey;
    ALTER TABLE public.meal_carousel_draft
      ALTER COLUMN created_meal_id TYPE bigint USING NULL;
    ALTER TABLE public.meal_carousel_draft
      ADD CONSTRAINT meal_carousel_draft_created_meal_id_fkey
        FOREIGN KEY (created_meal_id) REFERENCES public.meals(id) ON DELETE SET NULL;
  END IF;
END $$;

ALTER TABLE public.meal_carousel_draft ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'meal_carousel_draft'
      AND policyname = 'meal_carousel_draft_service_all'
  ) THEN
    CREATE POLICY "meal_carousel_draft_service_all" ON public.meal_carousel_draft
      FOR ALL USING (true);
  END IF;
END $$;
