-- =============================================================================
-- FLAG_CATEGORIES + FLAGS_CATEGORIES_FLAG
-- Top-level groupings (Grains, Meat, …) and which existing public.flags belong
-- to each. Load flag_categories first, then flags_categories_flag.
-- Requires public.flags to exist and match ids/names from Data Upload/flags.csv
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.flag_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz,
  updated_at timestamptz
);

-- Join: flag ∈ category (like flag_item links item ↔ flag)
CREATE TABLE IF NOT EXISTS public.flags_categories_flag (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flag_category_id bigint NOT NULL REFERENCES public.flag_categories (id) ON DELETE CASCADE,
  flag_id bigint NOT NULL REFERENCES public.flags (id) ON DELETE CASCADE,
  created_at timestamptz,
  updated_at timestamptz,
  CONSTRAINT flags_categories_flag_unique UNIQUE (flag_category_id, flag_id)
);

CREATE INDEX IF NOT EXISTS flags_categories_flag_flag_id_idx
  ON public.flags_categories_flag (flag_id);
CREATE INDEX IF NOT EXISTS flags_categories_flag_category_id_idx
  ON public.flags_categories_flag (flag_category_id);

-- If you created flag_categories before sort_order was removed, run:
-- DROP INDEX IF EXISTS public.flag_categories_sort_order_idx;
-- ALTER TABLE public.flag_categories DROP COLUMN IF EXISTS sort_order;
