-- =============================================================================
-- FLAGS + FLAG_ITEM — lookup + join (items ↔ flags)
--
-- Run in Supabase SQL Editor (or psql) after `public.items` exists.
-- Matches CSV columns: Data Upload/flags.csv, Data Upload/flag_item.csv
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.flag_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES public.items (id) ON DELETE CASCADE,
  flag_id bigint NOT NULL REFERENCES public.flags (id) ON DELETE CASCADE,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS flag_item_item_id_idx ON public.flag_item (item_id);
CREATE INDEX IF NOT EXISTS flag_item_flag_id_idx ON public.flag_item (flag_id);

-- Optional: one row per item+flag pair (uncomment if you want DB-level enforcement)
-- ALTER TABLE public.flag_item ADD CONSTRAINT flag_item_item_flag_unique UNIQUE (item_id, flag_id);

-- After you upload CSVs with explicit ids, bump sequences by running
-- `backend/sql/v4_6_legacy_namespace.sql` (includes flags + flag_item), or:
--   SELECT setval('public.flags_id_seq', COALESCE((SELECT MAX(id) FROM public.flags), 1));
--   SELECT setval('public.flag_item_id_seq', COALESCE((SELECT MAX(id) FROM public.flag_item), 1));
